name: Build and push docker-stacks containers 

on:
  push:
    # only pushes on master so we don't push intermediate results to dockerhub
    branches:
    - main
    paths:
    - '.github/workflows/docker-stack.yml'
  pull_request:

jobs:

  x86_64_cuda-foundation:
    name: Build and push images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: jupyter/docker-stacks
          ref: 2ace7f71087a
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: marorro/docker-stacks-foundation
          tags: |
            type=sha
            latest
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: github.event_name != 'pull_request'
      - name: Build and push docker-stacks-foundation
        uses: docker/build-push-action@v3
        with:
          context: docker-stacks-foundation
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          build-args: |
            ROOT_CONTAINER=nvidia/cuda:11.3.0-cudnn8-runtime-ubuntu20.04
#           ROOT_CONTAINER=nvidia/cuda:11.4.2-cudnn8-runtime-ubuntu20.04

      - name: Docker meta base-notebook
        id: docker_meta_base-notebook
        uses: docker/metadata-action@v4
        with:
          images: marorro/base-notebook
          tags: |
            type=sha
            latest
      - name: Build and push base-notebook
        uses: docker/build-push-action@v3
        with:
          context: base-notebook
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta_minimal-notebook.outputs.tags }}
          labels: ${{ steps.docker_meta_minimal-notebook.outputs.labels }}
          build-args: |
           BASE_CONTAINER=marorro/docker-stacks-foundation

      - name: Docker meta minimal-notebook
        id: docker_meta_minimal-notebook
        uses: docker/metadata-action@v4
        with:
          images: marorro/minimal-notebook
          tags: |
            type=sha
            latest
      - name: Build and push minimal-notebook
        uses: docker/build-push-action@v3
        with:
          context: minimal-notebook
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta_minimal-notebook.outputs.tags }}
          labels: ${{ steps.docker_meta_minimal-notebook.outputs.labels }}
          build-args: |
           BASE_CONTAINER=marorro/base-notebook

      - name: Docker meta scipy-notebook
        id: docker_meta_scipy-notebook
        uses: docker/metadata-action@v4
        with:
          images: marorro/scipy-notebook
          tags: |
            type=sha
            latest
      - name: Build and push scipy-notebook
        uses: docker/build-push-action@v3
        with:
          context: scipy-notebook
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta_scipy-notebook.outputs.tags }}
          labels: ${{ steps.docker_meta_scipy-notebook.outputs.labels }}
          build-args: |
           BASE_CONTAINER=marorro/minimal-notebook

      - name: Docker meta datascience-notebook
        id: docker_meta_datascience-notebook
        uses: docker/metadata-action@v4
        with:
          images: marorro/datascience-notebook
          tags: |
            type=sha
            latest
      - name: Build and push datascience-notebook
        uses: docker/build-push-action@v3
        with:
          context: datascience-notebook
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta_datascience-notebook.outputs.tags }}
          labels: ${{ steps.docker_meta_datascience-notebook.outputs.labels }}
          build-args: |
           BASE_CONTAINER=marorro/scipy-notebook
