name: Build and push containers

on:
  push:
    # only pushes on master so we don't push intermediate results to dockerhub
    branches:
    - main
  pull_request:

jobs:

  x86_64_cuda-foundation:
    name: Build and push images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: jupyter/docker-stacks
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: marorro/docker-stacks-foundation
          tags: |
            type=sha
            latest
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: github.event_name != 'pull_request'
      - name: Build and push docker-stacks-foundation
        uses: docker/build-push-action@v3
        with:
          context: docker-stacks-foundation
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          build-args: |
           ROOT_CONTAINER=nvidia/cuda:11.4.2-cudnn8-runtime-ubuntu20.04

      - name: Docker meta x86_64-base
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: marorro/x86_64-base
          tags: |
            type=sha
            latest
      - name: Build and push x86_64-base
        uses: docker/build-push-action@v3
        with:
          context: base-notebook
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          build-args: |
           ROOT_CONTAINER=marorro/docker-stacks-foundation
