name: Build and push e-containers

on:
  push:
    # only pushes on master so we don't push intermediate results to dockerhub
    branches:
    - main
  pull_request:
  workflow_run:
    workflows: [Build and push docker-stacks containers]
    types:
      - completed

jobs:

  x86_64_cuda-base:
    name: Build and push images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta base
        id: docker_meta_base
        uses: docker/metadata-action@v4
        with:
          images: marorro/gpu-base
          tags: |
            type=sha
            latest
      - name: Build and push base
        uses: docker/build-push-action@v3
        with:
          context: base
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta_base.outputs.tags }}
          labels: ${{ steps.docker_meta_base.outputs.labels }}


      - name: Docker meta gpu-notebook
        id: docker_meta_gpu-notebook
        uses: docker/metadata-action@v4
        with:
          images: marorro/single-user-gpu
          tags: |
            type=sha
            latest
      - name: Build and push single-user-gpu
        uses: docker/build-push-action@v3
        with:
          context: single-user-gpu
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta_gpu-notebook.outputs.tags }}
          labels: ${{ steps.docker_meta_gpu-notebook.outputs.labels }}
